data:
  root_dir: /home/yukun/codes/Multimodal_paper2/HARMF/data/Dataset_128-64_grid_mm-rs_250516
  train_list: train.txt
  val_list: val.txt
modalities:
  use_dem: true
  use_insar_vel: true
  use_rgb: true
model:
  backbone: swin_tiny
  drop_path_rate: 0.2
  drop_rate: 0.0
  modality_dims:
    dem: 3
    insar_vel: 3
    rgb: 3
  modality_norms:
    dem:
      max: 5749.44482421875
      mean: 3783.76513671875
      min: 548.5
      std: 967.0396728515625
    insar_vel:
      max: 0.1381572037935257
      mean: -0.006850511766970158
      min: -0.33521831035614014
      std: 0.014505097642540932
    rgb:
      band1:
        max: 15732.0
        mean: 1052.614293866453
        min: 0.0
        std: 672.6658132572438
      band2:
        max: 15832.0
        mean: 1021.5029089767321
        min: 1.0
        std: 546.432023170618
      band3:
        max: 16256.0
        mean: 704.6330336680454
        min: 0.0
        std: 511.3952055022167
  n_heads: 8
  num_classes: 2
  num_modalities: 3
  pretrained: true
  type: geminifusion
prediction:
  model_path: checkpoints/HARMF_sparsity05_128-64_data2_20250524/model_epoch_20.pth
  output_dir: work_dir/HARMF_sparsity05_128-64_data2_20250524_pred_best
training:
  batch_size: 16
  ckpt_dir: checkpoints/
  current_time: '20250903'
  learning_rate: 2.0e-05
  log_dir: logs/
  loss:
    ignore_index: 255
    losses:
    - gamma: 2.0
      name: focal
      weight: 0.7
    - name: boundary
      theta: 3.0
      weight: 0.3
    type: combined
  name: HARMF_sparsity05_128-64_data2
  num_epochs: 120
  num_workers: 16
  save_interval: 10
  scheduler:
    T_max: 100000
    eta_min: 1e-7
    type: cos
    warmup_iterations: 3000
  weight_decay: 0.05
